#!/bin/bash
rm './bin/FlyingCarpetLinux.zip'
qtdeploy build desktop ./gui/flyingcarpet
mkdir -p bin
cd ./gui/flyingcarpet/deploy
mv linux FlyingCarpet
zip -r '../../../bin/FlyingCarpetLinux.zip' FlyingCarpet
FlyingCarpet/flyingcarpet
