#!/bin/bash
rm './bin/Flying Carpet (Linux).zip'
qtdeploy build desktop ./gui/flyingcarpet
mkdir -p bin
cd ./gui/flyingcarpet/deploy
mv linux FlyingCarpet
zip -r '../../../bin/Flying Carpet (Linux).zip' FlyingCarpet
FlyingCarpet/flyingcarpet
